security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      clientId: client
      clientSecret: secret
    resource:
      userInfoUri: http://localhost:8080/user